baseURL = "https://blog.neuland-ingolstadt.de/"
languageCode = "de-de"
title = "Neuland Ingolstadt Blog"
theme = "PaperMod"

[params]
  imprint = "https://neuland-ingolstadt.de/impressum.htm"
  disableThemeToggle = true
